name: Sync All Repositories
on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sync script
        uses: actions/checkout@v4
        
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.GITCODE_SYNC_PRIVATE_KEY }}
          args: >-
            -o "IdentityFile=~/.ssh/id_ed25519"
            -o "StrictHostKeyChecking=no"  # 禁用主机密钥检查（可选）
          
      - name: Add GitCode host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan gitcode.net >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Test SSH connection (临时验证步骤，成功后可删除)
        run: |
          ssh -T git@gitcode.net
          
      - name: Sync all repositories
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN_GITHUB }}
          GITCODE_API_TOKEN: ${{ secrets.GITCODE_SYNC_TOKEN }}
          GITHUB_USERNAME: tsohnugo
          GITCODE_USERNAME: tsohnugo
        run: |
          python3 << 'EOF'
          # 同步脚本保持不变...
          EOF
