# Enable job 2025-05-08
name: tsohnugo gitee repos mirror periodic job

on:
  workflow_dispatch:
  pull_request:
    paths:
    - '.github/workflows/**'
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Mirror the github/tsohnugo org repos to gitee/tsohnugo.
      uses: Yikun/hub-mirror-action@v1.4
      with:
        src: github/tsohnugo
        dst: gitee/tsohnugo
        dst_key: ${{ secrets.SYNC_PRIVATE_KEY }}
        dst_token:  ${{ secrets.SYNC_TOKEN }}
        clone_style: ssh
        force_update: true
        debug: true

